---
- name: "Create route.yml files from templates"
  template:
    src: "route.j2"
    dest: "{{ tempdir }}/{{ item }}-route.yml"


- name: "Deploy routes"
  oc_obj:
    state: present
    name: "{{ item }}"
    namespace: "{{ cluster_prometheus_namespace }}"
    kind: Route
    files:
    - "{{ tempdir }}/{{ item }}-route.yml"
    #delete_after: true
