---
- name: Application Monitoring Operator Checkpoint Start
  hosts: all
  gather_facts: false
  tasks:
  - name: Set Application Monitoring Operator 'In Progress'
    run_once: true
    set_stats:
      data:
        installer_phase_application_monitoring_operator:
          title: "Application Monitoring Operator"
          playbook: "playbooks/prometheus-ocp/config.yml"
          status: "In Progress"
          start: "{{ lookup('pipe', 'date +%Y%m%d%H%M%SZ') }}"


- name: Configure Application Monitoring Operator
  hosts: oo_first_master
  roles:
    - role: /usr/share/ansible/openshift-ansible/roles/lib_utils
    - role: /usr/share/ansible/openshift-ansible/roles/lib_openshift
    - role: openshift_application_monitoring

- name: Application Monitoring Operator Checkpoint End
  hosts: all
  gather_facts: false
  tasks:
  - name: Set Application Monitoring Operator 'Complete'
    run_once: true
    set_stats:
      data:
        installer_phase_application_monitoring_operator:
          status: "Complete"
          end: "{{ lookup('pipe', 'date +%Y%m%d%H%M%SZ') }}"
